### ISSUE TITLE
Fringe Benefits not enabled in request cookies for Gelbooru

### ISSUE THREAD

**Issue by SPOOKEXE** [Inzaniak/sd-webui-ranbooru#12]
Fringe benefits is all the hidden content of the site that is not visible. To enable, you go to "My Account" -> Settings -> "Enable All Site Content" (note; does not require you to log in) and save at the bottom of the page.

Simple fix is to include the cookie "fringeBenefits" with the value of "yup" in the get request. Potentially make this an toggleable option in the widget.

For those wanting to apply this fix via a hard-coded value, see below.
![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/91944990/4a0bfd9f-b6e7-4ba7-bb99-cd3dc6b49d85)

**Comment by SmashinFries** [comment]
Do you know if any other implemented booru has fringe benefits? I'm thinking not, but asking just in case.

**Comment by SPOOKEXE** [comment]
Don't think many realize its a thing tbh

**Comment by Inzaniak** [comment]
I've merged the pull request. Thanks for your contribution!
