### ISSUE TITLE
[Feature Request] Excluding Tags Containing Specific Keywords

### ISSUE THREAD

**Issue by player99963** [Inzaniak/sd-webui-ranbooru#15]
Sometimes a user needs to exclude all tags related to a particular series, object, etc. It may be too cumbersome for the user to collect all the related tags and disable them.
In this case, it would be too cumbersome for the user to collect all the related tags and disable them.
What's more, some tags contain ":number", which will cause the generated image to be corrupted if it appears.
It would be nice to have a syntax that could be used in "Tags to Remove" to exclude tags that contain specific keywords.

**Comment by Inzaniak** [comment]
It is now possible to add an * to a word to remove all tags containing that specific string. Check the readme.
