### ISSUE TITLE
[Feature Request] Permanent Tags to Remove

### ISSUE THREAD

**Issue by player99963** [Inzaniak/sd-webui-ranbooru#16]
Due to the random nature of ranbooru, users often need to filter tags to avoid generating unwanted images.
Many of these tags are used every time, but it's a pain to manually save them somewhere else and re-paste them every time they are used.

I think it would be great if ranbooru could permanently save the Tags to Remove that the user has used.
Or let ranbooru can automatically read the content of a specific txt or csv file and use it as a tag for filtering.

**Comment by Inzaniak** [comment]
The script now has a file feature which enables the user to save tags to search or remove in one (or multiple) text files. Check the readme for the path.
