### ISSUE TITLE
tags from single post

### ISSUE THREAD

**Issue by simonmcnair** [Inzaniak/sd-webui-ranbooru#19]
I would like to use the tags from this to create an image:
https://danbooru.donmai.us/posts/6989698?q=princess_zelda

So I choose danbooru and put in the post id of 6989698, max pages 1 (shouldn't need this at all with a post_id ?)

I expect tags of:
1boy, 1girl, armor, blue eyes, brown hair, circlet, earrings, eyebrows hidden by hair, green headwear, green tunic, hat, jewelry, light brown hair, low-tied sidelocks, pointy ears, red background, shoulder armor, triforce, v-shaped eyebrows 

but the query is https://danbooru.donmai.us/posts.json?limit=100&page=0&id=6989698
and I get a bunch of random tags.

I would have expected the query to be:
https://danbooru.donmai.us/posts/6989698.json

Am I confused as to how it works please ?

**Comment by Inzaniak** [comment]
There was an error on how I managed the direct url for Danbooru, now it should work as intended.

**Comment by simonmcnair** [comment]
> There was an error on how I managed the direct url for Danbooru, now it should work as intended.

thank you ! :-)
