### ISSUE TITLE
[BUG] always using same prompt in txt2img batch mode

### ISSUE THREAD

**Issue by Inblac** [Inzaniak/sd-webui-ranbooru#2]
setting:  uncheck "Use same prompt for all images", batch count = 1, batch size = 3.

console show "Processing Multiple Prompts",  but the 3 result imgs using same prompt.

![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/10355228/c8432b69-93b0-4953-9638-dca6cc67cc43)

IN README：Use the same prompt for all images: This use the same prompt for all the generated images in the same batch. If not selected, each image will have a different prompt.

**Comment by Inzaniak** [comment]
Hi!
I can't seem to replicate this issue on my end. Can you check if you have accidentally wrote some tags in the **Post ID** section? It happened to me a few times, and for some reason it seems to grab only one prompt when you write anything in that box (even if it's not a valid ID).
