### ISSUE TITLE
repeated images/tags

### ISSUE THREAD

**Issue by rktvr** [Inzaniak/sd-webui-ranbooru#23]
i've noticed that when you generate larger batches that quite a lot of grabbed tags are repeated. out of 100 images, about 10~20 used the exact same tags from a previous image.
 this shouldn't happen when there are more than enough results based on your tags, there should be more than enough random images before it should ever start repeating.
you can reproduce it with any search, you'll notice that even with smaller batch counts it will start to repeat tags.

**Comment by Inzaniak** [comment]
Now the posts should be picked at random without any repeats.

**Comment by Inzaniak** [comment]
That's strange, I've tested on my end by doing same seed plus no shuffling of tags, but I've never got the same picture twice. There are a few things you could check on your end;
- Are you on the latest version of the extension?
- Have you set Sorting Order to High or Low? Right now this should still have repeats.
- Check the URL returned in the terminal to see if there are pictures with the same tags. It often happens on Booru to have the same picture repeated multiple times with small variations
