### ISSUE TITLE
gelbooru only works with at least 1Tags to Search (Pre) when using post ID

### ISSUE THREAD

**Issue by EaglePPP** [Inzaniak/sd-webui-ranbooru#26]
gelbooru only works with at least 1Tags to Search (Pre) when using post ID
If i wanna use a post rather than searching, it became impossible.
it needs at least 1 tag to enable, the tag doesnt really need to be relevant.

**Comment by Inzaniak** [comment]
Hey! I tried to replicate the issue, but I couldn't. I've tried opening a new tab and just putting an ID in the Post ID section and it worked as expected.
