### ISSUE TITLE
_ and space problem

### ISSUE THREAD

**Issue by EaglePPP** [Inzaniak/sd-webui-ranbooru#27]
hello my favourite little alien developer,

so there is a problem with _ and space,
when i use the tag_remove.txt
somehome i need to put in _ instead of spaces to make it work, despite im already checked the option "Convert _ to spaces"

**Comment by Inzaniak** [comment]
Hey! The "Convert _ to spaces" option is applied after getting the prompt from the booru and by design the extension expects "_" as these are the ones used on the boorus.
