### ISSUE TITLE
[Feature Request] Blacklisting Tags

### ISSUE THREAD

**Issue by LuckyLuigiX4** [Inzaniak/sd-webui-ranbooru#3]
First, please let me know if this is already a thing and I'm just an idiot.

A blacklisting system would be good to weed out certain tags that you may not want. Examples being blacklisting "1boy" or "loli" tags so they can't be used in generation.

**Comment by Inzaniak** [comment]
Hi!
Right now there are two ways to remove tags from a search:
- Using the **Tags to Search (pre)** option, this one uses the syntax of the booru to search, so adding a minus symbol in front of the tag will remove it from the search
- Using the **Tags to Remove (post)** option, this removes the tags after the search (so you actually search for the tag on the booru and then it is removed before of the generation)

There is also a list of tags which is automatically removed with the **Remove bad tags** option. This list right now is embedded into the code and cannot be changed and works in the same way as the **Tags to Remove (post)** option.

**Comment by LuckyLuigiX4** [comment]
Oh my god why didn't I think about using the minus symbol? Thank you this helps a lot
