### ISSUE TITLE
[bug] Using gelbooru,  KeyError: 'post'

### ISSUE THREAD

**Issue by ElizaPottinger** [Inzaniak/sd-webui-ranbooru#34]
Hey, when I use multiple search terms with gelbooru I am getting this message in the CLI and nothing is added to the prompt.

`Using gelbooru
https://gelbooru.com/index.php?page=dapi&s=post&q=index&json=1&limit=100&pid=70&tags=-animated+1girl+hug+pov
*** Error running before_process: E:\Stability Matrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-ranbooru\scripts\ranbooru.py
    Traceback (most recent call last):
      File "E:\Stability Matrix\Data\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 795, in before_process
        script.before_process(p, *script_args)
      File "E:\Stability Matrix\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-ranbooru\scripts\ranbooru.py", line 654, in before_process
        for post in data['post']:
    KeyError: 'post'`

![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/111184250/2161f48a-12af-4a33-9efd-cb8939b8dd4e)
![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/111184250/0287718b-8127-49b3-a780-2b6bbb4f2112)

**Comment by rktvr** [comment]
it means you have too many pages selected. you have to turn this setting down until it returns search results: 
![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/12204351/92d260bc-493d-451c-b183-05d23fd133ee)

**Comment by ElizaPottinger** [comment]
Awesome. Thanks for the reply!
