### ISSUE TITLE
Сompatibility with another extension

### ISSUE THREAD

**Issue by D0n-A** [Inzaniak/sd-webui-ranbooru#36]
Good day. Please add compatibility with [this ](https://github.com/Haoming02/sd-webui-tabs-extension) extension. In my humble opinion, this is a small visual bug due to the lack of the "Enable" checkbox in the extension.

An example of the image below: another extension is specifically enabled, and it is highlighted in green.
![01](https://github.com/Inzaniak/sd-webui-ranbooru/assets/38649081/1e5895e5-2a86-4f32-bd73-a69a65d9d8ea)

**Comment by Inzaniak** [comment]
Should be fixed with the pull request
