### ISSUE TITLE
[Feature Request] e621 Compatibility

### ISSUE THREAD

**Issue by VRArt1** [Inzaniak/sd-webui-ranbooru#4]
Could this be made compatible with e621?

**Comment by Inzaniak** [comment]
Hi!
I've checked e621 documentation and it's using a similar API to the other boorus, so it should be easy to implement it in the script. I'll add it in the next update.

**Comment by Inzaniak** [comment]
Added in commit:
51708d5c3856ab43d983d5e1fe66e08afa4c1a8f
