### ISSUE TITLE
Tags to Remove (Post) Not working?

### ISSUE THREAD

**Issue by LuckyLuigiX4** [Inzaniak/sd-webui-ranbooru#5]
The below screenshots are part of the example.

Tag Search (Pre)
![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/76882834/4dca9e8d-8204-4ec9-99ab-364f2d9cbc1f)

Tags to Remove (Post) (Also note its the same as Pre):
![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/76882834/166eb1e0-90d3-4601-a761-ba232afbd477)

Result Image Prompt (Note that there are duplicate tags, ones that shouldn't appear via the post input):
![image](https://github.com/Inzaniak/sd-webui-ranbooru/assets/76882834/bfdc5444-56c7-45a3-ae8e-ecfb3b9c7fe8)

I know I posted here a few days ago and realized I was just an idiot, but I really think this isnt working.

**Comment by Inzaniak** [comment]
Hi!
The values you insert in all the fields should be separated by commas otherwise it won't work correctly (I'm actually surprised it even searches with the words separated by spaces).
Doing this will work:
<img width="447" alt="image" src="https://github.com/Inzaniak/sd-webui-ranbooru/assets/5658274/c37115c3-635e-469d-bcc5-a3905e1c5834">

**Comment by LuckyLuigiX4** [comment]
> Hi! The values you insert in all the fields should be separated by commas otherwise it won't work correctly (I'm actually surprised it even searches with the words separated by spaces). Doing this will work: <img alt="image" width="447" src="https://user-images.githubusercontent.com/5658274/275175338-c37115c3-635e-469d-bcc5-a3905e1c5834.png">

Interesting. I found out that spaces work when I tried out the Gelbooru syntax with searching tag1 OR tag2 OR tag3... using { tag1 ~ tag2 ~ tag3}. I don't know how it would work using commas, but it worked with spaces so I rolled with it. I only use Gelbooru, so this method may not work for the other ones. However using the Gelbooru syntax and then adding the tags in the post search box exactly like you showed did work. I am unsure if I am dumb or if the documentation isn't specific on the correct way.

Another thing I have seen is that each tag in the prompt isn't seperated by a space 
(Ex: 1girl,short hair,t-shirt) rather than how I see most tag prompts (Ex: 1girl, short hair, t-shirt). I know this isn't related to my original problem but it's something I wish to know about.

**Comment by Inzaniak** [comment]
I've changed the readme to made it clear that you need to use comma separated values.
For your second question, from what I've seen adding spaces does not influence the result but consumes token. So, it's more effective to just remove the spaces and keep the commas.
